# Fancy Indexing

In [1]:
import numpy as np

In [2]:
x=np.arange(16)

In [3]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
x[3]

3

In [5]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [6]:
x[3:9:2]

array([3, 5, 7])

In [7]:
[x[3],x[5],x[8]]

[3, 5, 8]

In [8]:
ind=[3,5,8]

In [9]:
x[ind]

array([3, 5, 8])

In [10]:
ind=np.array([0,2],[1,3])

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [11]:
ind=np.array([[0,2],[1,3]])

In [12]:
x[ind]

array([[0, 2],
       [1, 3]])

In [13]:
X=x.reshape(4,-1)

In [14]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
row=np.array([0,1,2])
col=np.array([1,2,3])
x[row,col]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [16]:
X[row,col]

array([ 1,  6, 11])

In [17]:
x[0,col]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [18]:
X[0,col]

array([1, 2, 3])

In [19]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [20]:
col=[True,False,True,True]

In [21]:
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### numpy.array的比较

In [22]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
x<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [24]:
x>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [25]:
x<=3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [26]:
x>=3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [27]:
x==3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [28]:
2*x==24-4*x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [29]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
X<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [31]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
np.sum(x<=3)

4

In [33]:
np.count_nonzero(x<=3)

4

In [34]:
np.any(x==0)

True

In [35]:
np.any(x<0)

False

In [36]:
np.all(x>=0)

True

In [37]:
np.all(x>0)

False

In [38]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
np.sum(X%2==0)

8

In [41]:
np.sum(X%2==0,axis=1)

array([2, 2, 2, 2])

In [42]:
np.sum(X%2==0,axis=0)

array([4, 0, 4, 0])

In [45]:
np.all(X>0,axis=1)

array([False,  True,  True,  True])

In [46]:
np.sum((x>3)&(x<10))

6

In [47]:
np.sum((x%2==0)|(x>10))

11

In [48]:
np.sum(-(x==0))

TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

In [49]:
np.sum(~(x==0))

15

In [50]:
x[x<5]

array([0, 1, 2, 3, 4])

In [51]:
x[x%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [52]:
X[X[:,3]%3==0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])