# 聚合操作

In [1]:
import numpy as np
L=np.random.random(100)

In [2]:
L

array([0.43765488, 0.57282918, 0.62744868, 0.42246554, 0.46688355,
       0.5512003 , 0.34874676, 0.91056354, 0.46010135, 0.34841682,
       0.27152878, 0.74778004, 0.85685732, 0.75030845, 0.14069942,
       0.97517963, 0.10068178, 0.50545143, 0.57626865, 0.88225743,
       0.8881209 , 0.63808144, 0.35424529, 0.5192433 , 0.11785457,
       0.08626163, 0.29088361, 0.68440617, 0.99737407, 0.87521077,
       0.90150982, 0.57966723, 0.21759365, 0.30187377, 0.98931099,
       0.88651594, 0.66662754, 0.16641377, 0.8074124 , 0.99116303,
       0.16712993, 0.71742121, 0.98797336, 0.18756213, 0.75693627,
       0.26279181, 0.40019095, 0.54301745, 0.54970952, 0.03939611,
       0.1602185 , 0.29011364, 0.32013398, 0.72137963, 0.9397681 ,
       0.02988944, 0.99949644, 0.91480552, 0.58018619, 0.57104233,
       0.80978061, 0.97938541, 0.40997426, 0.438749  , 0.49466303,
       0.59185286, 0.56504841, 0.3315265 , 0.82257435, 0.90481063,
       0.01839565, 0.14475266, 0.2446446 , 0.06119297, 0.39339

In [3]:
sum(L)

52.48773138811642

In [4]:
np.sum(L)

52.48773138811644

In [5]:
big_array=np.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

AttributeError: module 'numpy' has no attribute 'rand'

In [6]:
big_array=np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

215 ms ± 12.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.71 ms ± 44.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
np.min(big_array)

2.2377796249362092e-07

In [8]:
np.max(big_array)

0.9999993286930728

In [9]:
big_array.min()

2.2377796249362092e-07

In [10]:
big_array.max()

0.9999993286930728

In [11]:
big_array.sum()

499966.7851288936

In [12]:
X=np.arange(16).reshape(4,-1)

In [13]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.sum(X)

120

In [15]:
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [16]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [17]:
np.prod(X)

0

In [18]:
np.prod(X+1)

2004189184

In [19]:
np.mean(X)

7.5

In [20]:
np.median(X)

7.5

In [21]:
v=np.array([1,1,2,2,10])
np.mean(v)

3.2

In [22]:
np.median(v)

2.0

In [23]:
np.percentile(big_array,q=50)

0.4999229645538436

In [24]:
np.median(big_array)

0.4999229645538436

In [25]:
np.percentile(big_array,q=100)

0.9999993286930728

In [26]:
for percent in [0,25,50,75,100]:
    print(np.percentile(big_array,q=percent))

2.2377796249362092e-07
0.25042246852052436
0.4999229645538436
0.7497321714567539
0.9999993286930728


In [27]:
np.var(big_array)

0.08325132660200205

In [28]:
np.std(big_array)

0.2885330598077143

In [29]:
x=np.random.normal(0,1,size=1000000)

In [30]:
np.mean(x)

-0.0018469062845254704

In [31]:
np.std(x)

1.000060629836334

In [32]:
x

array([-0.82537078,  1.58562574,  0.43105705, ..., -0.51426894,
        1.70986708,  0.83327794])

# 索引

In [33]:
np.min(x)

-5.146613672435438

In [34]:
np.argmin(x)

60933

In [35]:
x[60933]

-5.146613672435438

In [36]:
np.argmax(x)

834250

In [37]:
x[834250]

4.60523030063581

In [38]:
np.max(x)

4.60523030063581

### 排序和使用索引

In [39]:
x=np.arange(16)

In [40]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
np.random.shuffle(x)

In [42]:
x

array([10,  8,  9, 15, 13, 14,  4,  3,  0,  6,  5, 11, 12,  2,  1,  7])

In [43]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
x

array([10,  8,  9, 15, 13, 14,  4,  3,  0,  6,  5, 11, 12,  2,  1,  7])

In [45]:
x.sort()

In [46]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [47]:
X=np.random.randint(10,size=(4,4))

In [48]:
X

array([[6, 1, 2, 8],
       [3, 4, 3, 8],
       [1, 8, 9, 7],
       [0, 5, 8, 6]])

In [49]:
np.sort(X)

array([[1, 2, 6, 8],
       [3, 3, 4, 8],
       [1, 7, 8, 9],
       [0, 5, 6, 8]])

In [50]:
np.sort(X,axis=1)

array([[1, 2, 6, 8],
       [3, 3, 4, 8],
       [1, 7, 8, 9],
       [0, 5, 6, 8]])

In [51]:
np.sort(X,axis=0)

array([[0, 1, 2, 6],
       [1, 4, 3, 7],
       [3, 5, 8, 8],
       [6, 8, 9, 8]])

In [52]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
np.random.shuffle(x)

In [54]:
np.argsort(x)

array([ 2,  3,  8,  1,  6,  5,  9, 12,  4,  0,  7, 15, 11, 14, 13, 10],
      dtype=int64)

In [55]:
x

array([ 9,  3,  0,  1,  8,  5,  4, 10,  2,  6, 15, 12,  7, 14, 13, 11])

In [56]:
np.partition(x,3)

array([ 2,  1,  0,  3,  6,  5,  4,  7,  9,  8, 10, 12, 15, 14, 13, 11])

In [57]:
np.argpartition(x,3)

array([ 8,  3,  2,  1,  9,  5,  6, 12,  0,  4,  7, 11, 10, 13, 14, 15],
      dtype=int64)

In [58]:
X

array([[6, 1, 2, 8],
       [3, 4, 3, 8],
       [1, 8, 9, 7],
       [0, 5, 8, 6]])

In [59]:
np.argsort(x,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [60]:
np.argsort(X,axis=1)

array([[1, 2, 0, 3],
       [0, 2, 1, 3],
       [0, 3, 1, 2],
       [0, 1, 3, 2]], dtype=int64)

In [61]:
X

array([[6, 1, 2, 8],
       [3, 4, 3, 8],
       [1, 8, 9, 7],
       [0, 5, 8, 6]])

In [62]:
np.argsort(X,axis=0)

array([[3, 0, 0, 3],
       [2, 1, 1, 2],
       [1, 3, 3, 0],
       [0, 2, 2, 1]], dtype=int64)

In [63]:
np.argpartition(X,2,axis=1)

array([[1, 2, 0, 3],
       [0, 2, 1, 3],
       [0, 3, 1, 2],
       [0, 1, 3, 2]], dtype=int64)

In [64]:
X

array([[6, 1, 2, 8],
       [3, 4, 3, 8],
       [1, 8, 9, 7],
       [0, 5, 8, 6]])

In [65]:
np.argpartition(X,1,axis=1)

array([[1, 2, 0, 3],
       [0, 2, 1, 3],
       [0, 3, 2, 1],
       [0, 1, 2, 3]], dtype=int64)

In [66]:
X

array([[6, 1, 2, 8],
       [3, 4, 3, 8],
       [1, 8, 9, 7],
       [0, 5, 8, 6]])

In [67]:
argpatition?

Object `argpatition` not found.


In [68]:
np.argpatition?

Object `np.argpatition` not found.
