In [1]:
import numpy as np
import matplotlib.pyplot as plt

raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_Y=[0,0,0,0,0,1,1,1,1,1]
X_train=np.array(raw_data_X)
Y_train=np.array(raw_data_Y)
x=np.array([8.093607318,3.365731514])

In [2]:
%run KNN.py

In [3]:
predict_Y=KNN_classify(6,X_train,Y_train,x)

In [4]:
predict_Y

1

In [5]:
X_train.shape[0]

10

In [6]:
X_train.shape

(10, 2)

In [7]:
X_train.shape[1]

2

In [8]:
x.shape[0]

2

### 使用scikit-learn中的KNN

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
KNN_classifier=KNeighborsClassifier(n_neighbors=6)

In [12]:
KNN_classifier.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=6)

In [16]:
x=np.array([8.093607318,3.365731514])
KNN_classifier.predict(x)

ValueError: Expected 2D array, got 1D array instead:
array=[8.09360732 3.36573151].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [17]:
X_predict=x.reshape(1,-1)

In [18]:
X_predict

array([[8.09360732, 3.36573151]])

In [19]:
KNN_classifier.predict(X_predict)

array([1])

In [20]:
y_predict=KNN_classifier.predict(X_predict)

In [21]:
y_predict[0]

1

### 重新整理我们KNN的代码

In [22]:
%run KNN.PY

In [24]:
knn_clf=KNNClassifier(k=6)

In [25]:
knn_clf.fit(X_train,Y_train)

KNN(k=6)

In [26]:
y_predict=knn_clf.predict(X_predict)

In [27]:
y_predict

array([1])

In [28]:
y_predict[0]

1