In [1]:
import numpy

In [2]:
numpy.__version__

'1.19.2'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.19.2'

Python_list的特点

In [5]:
L=[i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[5]

5

In [7]:
L[5]=100

In [8]:
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [9]:
L[5]="machine"
L

[0, 1, 2, 3, 4, 'machine', 6, 7, 8, 9]

In [10]:
import array


In [11]:
arr=array.array('i',[i for i in range(10)])

In [12]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[5]

5

In [14]:
arr[5]=100

In [15]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [16]:
arr[5]="machinelearning"

TypeError: an integer is required (got type str)

# numpy.array

In [17]:
nparr=np.array([i for i in range(10)])

In [18]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
nparr[5]

5

In [20]:
nparr[5]=100

In [21]:
nparr[5]="machine"

ValueError: invalid literal for int() with base 10: 'machine'

In [23]:
nparry.dtype

NameError: name 'nparry' is not defined

In [24]:
nparr.dtype

dtype('int32')

In [25]:
nparr[5]=5.0

In [26]:
nparr.dtype

dtype('int32')

In [27]:
nparr[3]=3.14

In [28]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
nparr.dtype

dtype('int32')

In [30]:
nparr2=np.array([1,2,3.0])

In [31]:
nparr2.dtype

dtype('float64')

# 其它创建numpy.array的方法

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros.dtype

AttributeError: 'builtin_function_or_method' object has no attribute 'dtype'

In [34]:
np.zeros(10).dtype

dtype('float64')

In [35]:
np.zeros(10,dtype=10)

TypeError: Cannot interpret '10' as a data type

In [36]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
np.zeros(3,5)

TypeError: Cannot interpret '5' as a data type

In [38]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.zeros(shape=(3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [40]:
np.one((3,5))

AttributeError: module 'numpy' has no attribute 'one'

In [41]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.full((3,5),666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [43]:
np.full(full_value=666.0,shape=(3,5))

TypeError: full() got an unexpected keyword argument 'full_value'

In [44]:
np.full(fill_value=666.0,shape=(3,5))

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

# range

In [45]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [46]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
[i for i in range(0,20,0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [48]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [50]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [51]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

# np random

In [52]:
np.random.randint(0,10)

6

In [53]:
np.random.randint(0,10,10)

array([9, 1, 4, 9, 0, 3, 5, 5, 4, 7])

In [54]:
np.random.randint(0,1,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
np.random.randint(4,8,size=10)

array([4, 7, 7, 6, 4, 6, 7, 4, 5, 6])

In [56]:
np.random.randint(4,8,size=(3,5))

array([[7, 7, 4, 7, 4],
       [4, 6, 7, 6, 5],
       [5, 6, 6, 5, 7]])

In [57]:
np.random.seed(666)

In [56]:
np.random.randint(4,8,size=(3,5))

array([[7, 7, 4, 7, 4],
       [4, 6, 7, 6, 5],
       [5, 6, 6, 5, 7]])

In [56]:
np.random.randint(4,8,size=(3,5))

array([[7, 7, 4, 7, 4],
       [4, 6, 7, 6, 5],
       [5, 6, 6, 5, 7]])

In [58]:
np.random.random()

0.7004371218578347

In [59]:
np.random.random(10)

array([0.84418664, 0.67651434, 0.72785806, 0.95145796, 0.0127032 ,
       0.4135877 , 0.04881279, 0.09992856, 0.50806631, 0.20024754])

In [60]:
np.random.random((3,5))

array([[0.74415417, 0.192892  , 0.70084475, 0.29322811, 0.77447945],
       [0.00510884, 0.11285765, 0.11095367, 0.24766823, 0.0232363 ],
       [0.72732115, 0.34003494, 0.19750316, 0.90917959, 0.97834699]])

In [61]:
np.random.normal()

-1.6829007709843886

In [62]:
np.random.normal(10,100)

32.91852477040214

In [63]:
np.random.normal(10,100)

-165.66252234324833

In [64]:
np.random.normal(0,1,(3,5))

array([[ 0.84463262,  0.27721986,  0.85290153,  0.1945996 ,  1.31063772],
       [ 1.5438436 , -0.52904802, -0.6564723 , -0.2015057 , -0.70061583],
       [ 0.68713795, -0.02607576, -0.82975832,  0.29655378, -0.3126795 ]])

In [65]:
np.random.normal?


In [66]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution