# Numpy.array的基本操作

In [1]:
import numpy as np

In [2]:
x=np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x=np.arange(15).reshape(3,5)

In [5]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [6]:
x.ndim

2

In [7]:
x.shape

(3, 5)

In [8]:
x.size

15

### numpy.array的数据访问

In [9]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
x[0,2]

2

In [11]:
x[2,1]

11

In [12]:
x[0][1]

1

In [13]:
x[(0,0)]

0

In [14]:
x[(2,2)]

12

In [15]:
x[2,2]

12

In [16]:
x[0:5]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
x[0][0:]

array([0, 1, 2, 3, 4])

In [18]:
x[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [19]:
x[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
x[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [21]:
x[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [22]:
x[0]

array([0, 1, 2, 3, 4])

In [23]:
x[0,:]

array([0, 1, 2, 3, 4])

In [24]:
x.[0,:].ndim

SyntaxError: invalid syntax (<ipython-input-24-d82f3d6b81e2>, line 1)

In [25]:
x[0,:].ndim

1

In [26]:
x[:,0]

array([ 0,  5, 10])

In [27]:
subX=x[:2,:3]

In [28]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [29]:
subX[0,0]=100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [30]:
x

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [31]:
x[0,0]=0
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [33]:
subX=x[:2,:3].copy()

In [34]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [35]:
subX[0,0]=100

In [36]:
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [37]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [38]:
a=np.arange(10)

In [39]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
x.shape

(3, 5)

In [41]:
a.shape

(10,)

In [42]:
a.ndim

1

In [43]:
x.reshape(2,5)

ValueError: cannot reshape array of size 15 into shape (2,5)

In [44]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
x.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [46]:
A=a.reshape(2,5)

In [47]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
B=x.reshape(1,10)

ValueError: cannot reshape array of size 15 into shape (1,10)

In [50]:
B=a.reshape(1,10)

In [51]:
B.ndim

2

In [52]:
B.shape

(1, 10)

In [53]:
a.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [54]:
a.reshape(-1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [55]:
x.reshape(2,-1)

ValueError: cannot reshape array of size 15 into shape (2,newaxis)

In [56]:
a.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
a.reshape(3,-1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)