In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris=datasets.load_iris()

In [3]:
X=iris.data

In [4]:
Y=iris.target

In [5]:
X.shape

(150, 4)

In [6]:
Y.shape

(150,)

### train_test_split

In [7]:
X[:120]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
shuffle_indexes=np.random.permutation(len(X))

In [13]:
shuffle_indexes

array([ 54, 113,  31, 104, 125,  86,  36,  38,  72,   9, 105,   5, 140,
       135,  97,  35, 131,  70, 134, 141,   1, 111, 118,  60, 137,  69,
        13,   8, 107, 121, 128,  98,  71, 149,  93,  82, 132,  78, 116,
        32,  96,  20,  88, 108,  94, 126,  55,  92,   3,  49,  90, 133,
        59,  58,  47, 115,  75, 101, 124, 110,  18, 122,  64,  91,  84,
       148,  21,  53,  79, 136, 127,  57, 119,  10,  11,  61,  81, 109,
       120, 114,  66, 138,  74,  50,  34, 130,   0,  19,  67,  87,  52,
        26,  25,  40,  39,  30, 129, 123,  12, 103,  16,  56,  44,  89,
        76,  43,  51,  22,  95,   2,  62,   6,  27,  14,  45,  23,  99,
        24, 142, 145,  29,  42, 117, 112,  37,  65, 144,  48,   4,  63,
        17,  80,  77, 106,  73,  85, 147,  33, 139,  28, 102,  83,  15,
        41,  68,   7,  46, 100, 146, 143])

In [14]:
test_ratio=0.2
test_size=int(len(X)*test_ratio)

In [15]:
test_size

30

In [16]:
test_indexes=shuffle_indexes[:test_size]
train_indexes=shuffle_indexes[test_size:]

In [17]:
X_train=X[train_indexes]
Y_train=Y[train_indexes]

X_test=X[test_indexes]
Y_test=Y[test_indexes]

In [18]:
print(X_train.shape)
print(Y_train.shape)

(120, 4)
(120,)


In [19]:
print(X_test.shape)
print(Y_test.shape)

(30, 4)
(30,)


### 使用我们的算法

In [21]:
from model_selection import train_test_split

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)

In [25]:
print(X_train.shape)
print(Y_train.shape)

(120, 4)
(120,)


In [26]:
print(X_test.shape)
print(Y_test.shape)

(30, 4)
(30,)


In [27]:
from KNN import KNNClassifier

In [28]:
my_knn_clf=KNNClassifier(k=3)

In [29]:
my_knn_clf.fit(X_train,Y_train)

KNN(k=3)

In [30]:
y_predict=my_knn_clf.predict(X_test)

In [31]:
y_predict

array([1, 2, 0, 2, 2, 1, 0, 0, 2, 0, 2, 0, 2, 2, 1, 0, 2, 2, 2, 2, 0, 2,
       2, 1, 2, 1, 0, 0, 2, 2])

In [33]:
Y_test

array([1, 2, 0, 2, 2, 1, 0, 0, 1, 0, 2, 0, 2, 2, 1, 0, 2, 1, 2, 2, 0, 2,
       2, 1, 2, 1, 0, 0, 2, 2])

In [34]:
sum(y_predict==Y_test)

28

In [35]:
sum(y_predict==Y_test)/len(Y_test)

0.9333333333333333

### sklearn中的train_test_split

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=666)

In [38]:
print(X_train.shape)
print(Y_train.shape)

(120, 4)
(120,)


In [39]:
print(X_test.shape)
print(Y_test.shape)

(30, 4)
(30,)
